### ISSUE TITLE
How to install on ubuntu

### ISSUE THREAD

**Issue by Technoturnovers** [n1nj4sec/memorpy#1]
I need to install memorpy on ubuntu so i can use it with Pupy, but it requires python win32 extensions that aren't available on ubuntu. Is there any way to load it on Pupy?

**Comment by n1nj4sec** [comment]
Memorpy only works on windows (I mean to read/write memory). But you can copy memorpy to your pupy packages/windows/all/ repository and remotely load it from memory if you have an opened session on a windows host. You will also needs some pywin32 .pyd like win32api, win32con and win32security you have to put in packages/windows/x86 or x64

**Comment by Technoturnovers** [comment]
Where do i get the pyd files?

**Comment by n1nj4sec** [comment]
download [pywin32](https://sourceforge.net/projects/pywin32). You can install it on a windows and retrieve the .pyd from C:\Python27\Lib or recompile the .pyd from sources

**Comment by Technoturnovers** [comment]
It worked, thanks!

**Comment by n1nj4sec** [comment]
No problem :) I also added memorpy dependencies autoloading on the pupy repo : 
```
>> run load_package memorpy
[+] package loaded !
>> run pyshell 
>>> from memorpy import *
>>> mw=MemWorker("notepad")
>>> l=[x for x in mw.umem_search("this is a test")]
>>> l
[<Addr: 0x00231650>]
```
