### ISSUE TITLE
How to write to specific memory address?

### ISSUE THREAD

**Issue by reillychase** [n1nj4sec/memorpy#13]
I already know the memory address that I want to change, so no use in looking for it with the locator function. However there seems to be no way to do this:

```
from memorpy import *
mw=MemWorker(name="some-process.exe")
a = <Addr: 0x004BC97>
a.write(1)
```

It seems to be a python limitation (no ability to store a memory address, can only reference the address of the previous instruction with _), is there a way to do what I am trying to do?

**Comment by n1nj4sec** [comment]
don't hesitate to have a look at the code it's pretty small and easy to understand 
```
a=mw.Address(0x12345)
a.write(42, 'uint')
```

**Comment by reillychase** [comment]
Thanks! Will do. This would be a good one to add to the readme I think
