### ISSUE TITLE
SunOS Support

### ISSUE THREAD

**Issue by alxchk** [n1nj4sec/memorpy#8]
Hi!

It's possible to reuse  Linux backend to be used in SunOS. To do so next things should be done:
1. Migration to psutil (SunOS have binary proc, and in psutil there is already code, which can be reused between linux and solaris).
2. Search C library using ctypes.util.find_library("c")
3. Avoiding to use ptrace (looks like there is no need to attach to process to to read address space)
4. Use /as instead of /mem
5. Do not treat absence of open64 as absence of Large file support.

I can write patch/PR request this, it this looks acceptable for you (1)

**Comment by n1nj4sec** [comment]
Hi !
Sure it would be nice to have SunOS support ! However I'd like to keep needing 0 dependencies for memorpy, so perhaps you can create a new file SunOSProcess.py, inherit BaseProcess and only load this file on SunOS so linux keeps having 0 necessary dependencies :)
Or if you are courageous enough, implement everything in ctypes ! (I admit I'm myself a bit lazy sometimes https://github.com/n1nj4sec/memorpy/blob/master/memorpy/OSXProcess.py#L87)

**Comment by n1nj4sec** [comment]
Thanks for your PR ! :)
